-- create a new TYPE called grocery and a new TABLE called shopping_list. Table will contain 6 columns and you will need to decide which SQL data types to use for each column

CREATE TABLE IF NOT EXISTS shopping_list (
  product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name TEXT NOT NULL,
  price decimal(12, 2) NOT NULL,
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  checked BOOLEAN DEFAULT false,
  category grocery NOT NULL
);

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
)


